inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop/cop/internal_affairs

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  NewCops: disable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Layout/LineLength:
  Max: 80 # default: 120
  AllowedPatterns:
    - '^\s*# .*https?:\/\/.+\[.+\]\.?$' # Allow long asciidoc links

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/InterpolationCheck:
  Exclude:
    - spec/**/*.rb

# When the `edge-rubocop` build is red, and we decide to disable the cop,
# the rest of the builds become red if the cop has not yet been released.
# Instead of waiting for RuboCop releases to make `edge-rubocop` green,
# we prefer keeping disable directives here and there and check if they
# are still needed once in a while.
Lint/RedundantCopDisableDirective:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - '**/*.rake'

Naming/FileName:
  Exclude:
    - lib/rubocop-capybara.rb

Naming/InclusiveLanguage:
  Enabled: true
  CheckStrings: true
  FlaggedTerms:
    ' a offense':
      Suggestions:
        - an offense
    auto-correct:
      Suggestions:
        - autocorrect
    auto_correct:
      Suggestions:
        - autocorrect
    ' a violation':
      Suggestions:
        - an offense
    behaviour:
      Suggestions:
        - behavior
    offence:
      Suggestions:
        - offense
    'does not registers':
      Suggestions:
        - does not register
    violation:
      Suggestions:
        - offense
    'register no offense':
      Suggestions:
        - registers no offense

RSpec:
  Language:
    Expectations:
      - expect_correction
      - expect_no_offenses
      - expect_offense

RSpec/ExampleLength:
  CountAsOne:
    - heredoc
  Max: 11

RSpec/DescribeClass:
  Exclude:
    - spec/project/**/*.rb

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/rubocop/cop/capybara/mixin/**/*.rb

RSpec/MultipleExpectations:
  Max: 2

Style/FormatStringToken:
  Exclude:
    - spec/rubocop/**/*.rb

Style/RequireOrder:
  Enabled: true

# Enable some of RuboCop's pending cops.

Layout/LineContinuationSpacing:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
Lint/AmbiguousOperatorPrecedence:
  Enabled: true
Lint/NonAtomicFileOperation:
  Enabled: true
Style/EmptyHeredoc:
  Enabled: true
Style/RedundantHeredocDelimiterQuotes:
  Enabled: true
Style/RedundantStringEscape:
  Enabled: true
Style/ReturnNilInPredicateMethodDefinition:
  Enabled: true

# Enable pending rubocop-performance cops.

Performance/AncestorsInclude:
  Enabled: true
Performance/BlockGivenWithExplicitBlock:
  Enabled: true
Performance/CollectionLiteralInLoop:
  Enabled: true
Performance/ConstantRegexp:
  Enabled: true
Performance/MapCompact:
  Enabled: true
Performance/MapMethodChain:
  Enabled: true
Performance/MethodObjectAsBlock:
  Enabled: true
Performance/RedundantEqualityComparisonBlock:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantSplitRegexpArgument:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringIdentifierArgument:
  Enabled: true
Performance/StringInclude:
  Enabled: true
Performance/Sum:
  Enabled: true
