= Usage

You need to tell RuboCop to load the Capybara extension.
There are three ways to do this:

== RuboCop configuration file

Put this into your `.rubocop.yml`:

----
plugins: rubocop-capybara
----

or, if you are using several extensions:

----
plugins:
  - rubocop-capybara
  - rubocop-performance
----

Now you can run `rubocop` and it will automatically load the RuboCop Capybara
cops together with the standard cops.

NOTE: The plugin system is supported in RuboCop 1.72+. In earlier versions, use `require` instead of `plugins`.

== Command line

[source,bash]
----
$ rubocop --plugin rubocop-capybara
----

== Rake task

[source,ruby]
----
RuboCop::RakeTask.new do |task|
  task.plugins << 'rubocop-capybara'
end
----

== File paths to be inspected

By default, `rubocop-capybara` only inspects code in files whose paths match the following regular expression.

[source,yaml]
----
Capybara:
  Include:
    - '**/*_spec.rb'
    - '**/spec/**/*'
    - '**/test/**/*'
    - '**/*_steps.rb'
    - '**/features/step_definitions/**/*'
----

You can override this setting in your config file by setting `Include`:

[source,yaml]
----
# Inspect files in `inspection/` directory
Capybara:
  Include:
    - '**/inspection/**/*'
----

[source,yaml]
----
# Inspect only files ending with `_inspection.rb`
Capybara:
  Include:
    - '**/*_inspection.rb'
----

NOTE: Please keep in mind that merge mode for `Include` is set to override the default settings, so if you intend to add a path while keeping the default paths, you should include the default `Include` paths in your configuration.
